#!/bin/sh
cd ${0%/*} || exit 1    # Run from this directory

./Allwclean

# Parse arguments for library compilation
targetType=libso
. $WM_PROJECT_DIR/wmake/scripts/AllwmakeParseArguments
set -x

#wmake $targetType turbulentTransport
wmake $targetType 

#------------------------------------------------------------------------------
